### ISSUE TITLE
... great work! what about a video encoder like avconv?

### ISSUE THREAD

**Issue by binarykitchen** [audiocogs/ogg.js#1]
awesome, i'm very glad to see this trend, people trying to port video stuff to javascript.

i've been trying to port avconv for ages without success, see:
https://gist.github.com/binarykitchen/5230096
https://gist.github.com/binarykitchen/5329825

have asked kripken (Alon) for help but i am still stuck with this one:
https://github.com/kripken/emscripten/issues/1042

i am unable to read local files for video encoding. maybe you can have a look there and give me clues? because i think you must have solved this somehow withing the compilation process for oggvorbis.js

thanks a lot. my aim is to develop an online web app where deaf people can communicate with each other in sign language.

cheers
michael

**Comment by devongovett** [comment]
Well the way I did it was write a C binding that could be called into by pure JavaScript and the [Aurora.js](https://github.com/audiocogs/aurora.js) framework.  Looks like you're trying to go the pure C command line route.  It might be better to make up JavaScript API bindings instead of relying on the command line program.  

Also, ffmpeg/avconv is a HUGE library with lots of platform specific stuff.  It's almost 10 MB as a binary, so I'd imagine it would be almost double that when compiled to JS -- not particularly optimized for downloading over the network you'd say.  It would be cool, so don't let this discourage you, but the approach I've been taking is to port over the most popular codecs either by hand or using Emscripten as needed and create a "web-native" framework for it.  Some of the blocking C file reading and conversion techniques used in these libraries don't really scale well to JavaScript.  In Aurora.js we stream and decode only as needed, which is why we are able to get CPU usage so low.

So far we've mostly focused on audio, though I've [dabbled](https://github.com/devongovett/jsmpeg) with video and there is Broadway.js too, but those are mostly cool demos and probably won't scale to playing back 1080p HD movies anytime soon without some serious hardware support.  See [here](http://blog.aventine.se/post/22679577526/broadway-and-h264) for more on that.  You can find all of the other codecs we've ported on our [Github](https://github.com/audiocogs/) page.

(Closing this issue since it isn't really an issue with this project, but feel free to keep discussing!)

**Comment by devongovett** [comment]
Just saw you mentioned encoding too, and that's something I'd like to tackle at least with audio stuff at some point (have to find the time...).  Video encoding has the same problems as decoding, except that it is probably even more CPU intensive than decoding.  It would be a very cool little demo on a small scale initially, but as I mentioned above, we need some more APIs from browsers to use multicore architectures more efficiently, SIMD instructions, GPUs (e.g. WebCL), etc. before JS will really be able to compete with the likes of ffmpeg and other native encoders...  But, that said, it takes someone like you who is crazy enough to do it and show that it's possible in order to change the thinking and make those features come to browsers more quickly.  After all, browser makers are here to serve developers, and if there is something we can't do, they need to help make it happen. :)

**Comment by binarykitchen** [comment]
thanks for that. look, i already have investigated all that what you have mentioned, i.e. broadway. none of that stuff comes in question because i'm only interested in javascript video encoding, not decoding.

and as a deaf person i am not interested in audio. have a look at www.videomail.io ... it works fine but is using web sockets for video encoding. hence the limitation to record videos up to 2 minutes max. if there is a javascript video encoder, then probably speed is much better and can increase limit to ~5 minutes.

you see, i am talking about minutes, not encoding a 2 hours movie. this should be mission possible for javascript. agreed, i'm crazy but for a good reason. videomail.io is nice, more and more people use it so worth a shot.

and about avconv, one correction: it is not that huge if you compile it only with the selected codecs you need and disable everything else. look at https://gist.github.com/binarykitchen/5230096 and you see i have added lots of `--disable-xxx` flags

all i want is simply to encode an image sequence to a video in javascript and that's all.
